// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	file_mgmt "FileMgmtMicroservice/restapi/operations/file_mgmt"

	middleware "github.com/go-openapi/runtime/middleware"

	mock "github.com/stretchr/testify/mock"
)

// HandlerFunctions is an autogenerated mock type for the HandlerFunctions type
type HandlerFunctions struct {
	mock.Mock
}

// GetFile provides a mock function with given fields: params
func (_m *HandlerFunctions) GetFile(params file_mgmt.GetFileParams) middleware.Responder {
	ret := _m.Called(params)

	var r0 middleware.Responder
	if rf, ok := ret.Get(0).(func(file_mgmt.GetFileParams) middleware.Responder); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(middleware.Responder)
		}
	}

	return r0
}

// ListFile provides a mock function with given fields:
func (_m *HandlerFunctions) ListFile() middleware.Responder {
	ret := _m.Called()

	var r0 middleware.Responder
	if rf, ok := ret.Get(0).(func() middleware.Responder); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(middleware.Responder)
		}
	}

	return r0
}

// UploadFile provides a mock function with given fields: params
func (_m *HandlerFunctions) UploadFile(params file_mgmt.UploadFileParams) middleware.Responder {
	ret := _m.Called(params)

	var r0 middleware.Responder
	if rf, ok := ret.Get(0).(func(file_mgmt.UploadFileParams) middleware.Responder); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(middleware.Responder)
		}
	}

	return r0
}
