// Code generated by go-swagger; DO NOT EDIT.

package file_mgmt

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewGetFileParams creates a new GetFileParams object
// no default values defined in spec.
func NewGetFileParams() GetFileParams {

	return GetFileParams{}
}

// GetFileParams contains all the bound params for the get file operation
// typically these are obtained from a http.Request
//
// swagger:parameters getFile
type GetFileParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*File name to be downloaded.
	  In: header
	*/
	FileName *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetFileParams() beforehand.
func (o *GetFileParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if err := o.bindFileName(r.Header[http.CanonicalHeaderKey("fileName")], true, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindFileName binds and validates parameter FileName from header.
func (o *GetFileParams) bindFileName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false

	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.FileName = &raw

	return nil
}
