// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	file_mgmt "FileMgmtMicroservice/restapi/operations/file_mgmt"

	middleware "github.com/go-openapi/runtime/middleware"

	mock "github.com/stretchr/testify/mock"
)

// UploadInterface is an autogenerated mock type for the UploadInterface type
type UploadInterface struct {
	mock.Mock
}

// UploadFile provides a mock function with given fields: params
func (_m *UploadInterface) UploadFile(params file_mgmt.UploadFileParams) middleware.Responder {
	ret := _m.Called(params)

	var r0 middleware.Responder
	if rf, ok := ret.Get(0).(func(file_mgmt.UploadFileParams) middleware.Responder); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(middleware.Responder)
		}
	}

	return r0
}
