// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "API Specification for FILE CRUD operation.",
    "title": "API Specification for FILE CRUD operation.",
    "contact": {
      "email": "vibhordubey333@gmail.com"
    },
    "license": {
      "name": "MIT",
      "url": "https://github.com/vibhordubey333"
    },
    "version": "1.0.0"
  },
  "host": "localhost:7777",
  "basePath": "/v1",
  "paths": {
    "/fileMgmt/getFile": {
      "get": {
        "description": "Get a file from storage",
        "produces": [
          "application/zip"
        ],
        "tags": [
          "fileMgmt"
        ],
        "summary": "Get a file from storage",
        "operationId": "getFile",
        "parameters": [
          {
            "type": "string",
            "description": "File name to be downloaded.",
            "name": "fileName",
            "in": "header"
          }
        ],
        "responses": {
          "200": {
            "description": "File Downloaded",
            "schema": {
              "type": "file"
            }
          },
          "500": {
            "description": "Server Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/fileMgmt/listFile": {
      "get": {
        "description": "List all files.",
        "produces": [
          "application/json"
        ],
        "tags": [
          "fileMgmt"
        ],
        "summary": "List all the files.",
        "operationId": "listFiles",
        "responses": {
          "200": {
            "description": "ListingFiles",
            "schema": {
              "type": "object",
              "properties": {
                "fileName": {
                  "description": "File Lists.",
                  "type": "array",
                  "items": {
                    "type": "object"
                  }
                },
                "message": {
                  "description": "File upload message",
                  "type": "string"
                }
              }
            }
          },
          "500": {
            "description": "Server Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/fileMgmt/uploadFile": {
      "post": {
        "description": "Upload a file to DB",
        "consumes": [
          "multipart/form-data"
        ],
        "tags": [
          "fileMgmt"
        ],
        "summary": "Upload a File",
        "operationId": "uploadFile",
        "parameters": [
          {
            "type": "file",
            "description": "The file to be uploaded",
            "name": "inputFile",
            "in": "formData",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "File Uploaded Successfully",
            "schema": {
              "type": "object",
              "properties": {
                "code": {
                  "description": "Response Code",
                  "type": "string"
                },
                "message": {
                  "description": "File upload message",
                  "type": "string"
                }
              }
            }
          },
          "500": {
            "description": "Server Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "string"
        },
        "message": {
          "type": "string"
        }
      }
    }
  },
  "tags": [
    {
      "description": "API Specification for TAR CRUD operation.",
      "name": "fileMgmt",
      "externalDocs": {
        "description": "Find out more",
        "url": "https://github.com/vibhordubey333"
      }
    }
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "API Specification for FILE CRUD operation.",
    "title": "API Specification for FILE CRUD operation.",
    "contact": {
      "email": "vibhordubey333@gmail.com"
    },
    "license": {
      "name": "MIT",
      "url": "https://github.com/vibhordubey333"
    },
    "version": "1.0.0"
  },
  "host": "localhost:7777",
  "basePath": "/v1",
  "paths": {
    "/fileMgmt/getFile": {
      "get": {
        "description": "Get a file from storage",
        "produces": [
          "application/zip"
        ],
        "tags": [
          "fileMgmt"
        ],
        "summary": "Get a file from storage",
        "operationId": "getFile",
        "parameters": [
          {
            "type": "string",
            "description": "File name to be downloaded.",
            "name": "fileName",
            "in": "header"
          }
        ],
        "responses": {
          "200": {
            "description": "File Downloaded",
            "schema": {
              "type": "file"
            }
          },
          "500": {
            "description": "Server Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/fileMgmt/listFile": {
      "get": {
        "description": "List all files.",
        "produces": [
          "application/json"
        ],
        "tags": [
          "fileMgmt"
        ],
        "summary": "List all the files.",
        "operationId": "listFiles",
        "responses": {
          "200": {
            "description": "ListingFiles",
            "schema": {
              "type": "object",
              "properties": {
                "fileName": {
                  "description": "File Lists.",
                  "type": "array",
                  "items": {
                    "type": "object"
                  }
                },
                "message": {
                  "description": "File upload message",
                  "type": "string"
                }
              }
            }
          },
          "500": {
            "description": "Server Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/fileMgmt/uploadFile": {
      "post": {
        "description": "Upload a file to DB",
        "consumes": [
          "multipart/form-data"
        ],
        "tags": [
          "fileMgmt"
        ],
        "summary": "Upload a File",
        "operationId": "uploadFile",
        "parameters": [
          {
            "type": "file",
            "description": "The file to be uploaded",
            "name": "inputFile",
            "in": "formData",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "File Uploaded Successfully",
            "schema": {
              "type": "object",
              "properties": {
                "code": {
                  "description": "Response Code",
                  "type": "string"
                },
                "message": {
                  "description": "File upload message",
                  "type": "string"
                }
              }
            }
          },
          "500": {
            "description": "Server Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "string"
        },
        "message": {
          "type": "string"
        }
      }
    }
  },
  "tags": [
    {
      "description": "API Specification for TAR CRUD operation.",
      "name": "fileMgmt",
      "externalDocs": {
        "description": "Find out more",
        "url": "https://github.com/vibhordubey333"
      }
    }
  ]
}`))
}
