// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	middleware "github.com/go-openapi/runtime/middleware"
	mock "github.com/stretchr/testify/mock"
)

// ListInterface is an autogenerated mock type for the ListInterface type
type ListInterface struct {
	mock.Mock
}

// ListFile provides a mock function with given fields:
func (_m *ListInterface) ListFile() middleware.Responder {
	ret := _m.Called()

	var r0 middleware.Responder
	if rf, ok := ret.Get(0).(func() middleware.Responder); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(middleware.Responder)
		}
	}

	return r0
}
