// Code generated by go-swagger; DO NOT EDIT.

package file_mgmt

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/runtime"

	"FileMgmtMicroservice/filemanagement/models"
)

// GetFileOKCode is the HTTP code returned for type GetFileOK
const GetFileOKCode int = 200

/*GetFileOK File Downloaded

swagger:response getFileOK
*/
type GetFileOK struct {

	/*
	  In: Body
	*/
	Payload io.ReadCloser `json:"body,omitempty"`
}

// NewGetFileOK creates GetFileOK with default headers values
func NewGetFileOK() *GetFileOK {

	return &GetFileOK{}
}

// WithPayload adds the payload to the get file o k response
func (o *GetFileOK) WithPayload(payload io.ReadCloser) *GetFileOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get file o k response
func (o *GetFileOK) SetPayload(payload io.ReadCloser) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetFileOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetFileInternalServerErrorCode is the HTTP code returned for type GetFileInternalServerError
const GetFileInternalServerErrorCode int = 500

/*GetFileInternalServerError Server Error

swagger:response getFileInternalServerError
*/
type GetFileInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetFileInternalServerError creates GetFileInternalServerError with default headers values
func NewGetFileInternalServerError() *GetFileInternalServerError {

	return &GetFileInternalServerError{}
}

// WithPayload adds the payload to the get file internal server error response
func (o *GetFileInternalServerError) WithPayload(payload *models.Error) *GetFileInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get file internal server error response
func (o *GetFileInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetFileInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetFileDefault error

swagger:response getFileDefault
*/
type GetFileDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetFileDefault creates GetFileDefault with default headers values
func NewGetFileDefault(code int) *GetFileDefault {
	if code <= 0 {
		code = 500
	}

	return &GetFileDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get file default response
func (o *GetFileDefault) WithStatusCode(code int) *GetFileDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get file default response
func (o *GetFileDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get file default response
func (o *GetFileDefault) WithPayload(payload *models.Error) *GetFileDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get file default response
func (o *GetFileDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetFileDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
