swagger: '2.0'
info:
  description: API Specification for FILE CRUD operation.
  version: 1.0.0
  title: API Specification for FILE CRUD operation.
  contact:
    email: vibhordubey333@gmail.com
  license:
    name: MIT
    url: 'https://github.com/vibhordubey333'
host: localhost:7777
basePath: /v1
tags:
  - name: fileMgmt
    description: API Specification for TAR CRUD operation.
    externalDocs:
      description: Find out more
      url: 'https://github.com/vibhordubey333'
consumes:
  - application/json
produces:
  - application/json
schemes:
  - http
paths:
  '/fileMgmt/uploadFile':
    post:
      tags:
        - fileMgmt
      summary: Upload a File
      description: Upload a file to DB
      operationId: uploadFile
      consumes:
        - multipart/form-data
      parameters:
        - name: inputFile
          type: file
          in: formData
          description: The file to be uploaded
          required: true
      responses:
        200:
          description: File Uploaded Successfully
          schema:
            type: object
            properties:
              code:
                type: string
                description: Response Code
              message:
                type: string
                description: File upload message
        500 :
          description: Server Error   
          schema:
            $ref: "#/definitions/error"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
            
  '/fileMgmt/getFile':
    get:
      tags:
        - fileMgmt
      summary: Get a file from storage
      description: Get a file from storage
      operationId: getFile
      produces: 
        - application/zip
      parameters:
        - in: header
          name: fileName
          type: string
          description: File name to be downloaded.
      responses:
        200:
          description: File Downloaded
          schema:
            type: file
        500 :
          description: Server Error
          schema:
            $ref: "#/definitions/error"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
            
  '/fileMgmt/listFile':
    get:
      tags:
        - fileMgmt
      summary: List all the files.
      description: List all files.
      operationId: listFiles
      produces:
        - application/json
      responses:
        200:
          description: ListingFiles
          schema:
            type: object
            properties:
              message:
                type: string
                description: File upload message
              fileName:
                type: array
                items:
                  type: object
                description: File Lists.
        500 :
          description: Server Error   
          schema:
            $ref: "#/definitions/error"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
            
definitions:
    error:
      type: object
      required:
        - message
      properties:
        code:
          type: string
        message:
          type: string
